### ISSUE TITLE
SharpDX usage

### ISSUE THREAD

**Issue by Nikolsi** [jwollen/SharpVulkan#3]
Hi, I would like to say thank you for what are you doing and providing the Sharp library. 
I have a question, is it possible to use Vulkan without any external Api like SharpDX or OpenGl?

**Comment by jwollen** [comment]
Vulkan is independent from OpenGL/DX. What functionality are you referring to?

**Comment by Nikolsi** [comment]
Sorry, probably I was wrong. 
I have figured that you are using SharpDX to create a window for rendering, right? 
Is it possible to make rendering without GL/DX?

**Comment by jwollen** [comment]
Yes, that's only for creating the window, since it's very convenient. No DriectX involved. You can get your window handle from anywhere, e.g. WinForms on Windows.
