### ISSUE TITLE
Vertex shader

### ISSUE THREAD

**Issue by Nikolsi** [jwollen/SharpVulkan#5]
Hello, I have tried to make some tests similar to your sample MiTri and I wanted to create some polygon primitives, e.g rectangle. I have tried to make a vertex array like :

var vertices = new[,]
{
      { -0.5f,  0.5f, 0.0f, 0.0f, 1.0f, 0.0f }, // Top-Left
      {  0.5f,  0.5f, 0.0f, 0.0f, 0.0f, 1.0f }, // Top-right
      {  0.5f, -0.5f, 0.0f, 1.0f, 0.0f, 0.0f }, // Bottom-right
      { -0.5f, -0.5f, 0.0f, 1.0f, 1.0f, 0.0f }, // Bottom-left
};
and in line setted to 4
// Draw vertices
            commandBuffer.Draw(4, 1, 0, 0);
But it still draws triangle. How can I play with vertexes to draw different shapes?
Thank you in advance

**Comment by jwollen** [comment]
Geometry is made up of triangles. For a rectangle you have to specify two triangles, i.e. 6 vertices. Alternatively you can set the `PrimitiveTopology` to `TriangleStrip`.

If you are new to computer graphics, I suggest looking for Direct3D or OpenGL tutorials. The basic concepts are the same. Most Vulkan resources assume that you know how the older APIs work.

**Comment by Nikolsi** [comment]
Omg, I forgot about that. That geometry made of triangles. Right.
Thank you 😊
