### ISSUE TITLE
Bug in PhysicalDevice.GetFormatProperties

### ISSUE THREAD

**Issue by bdachev** [jwollen/SharpVulkan#6]
Hi jwollen, 
First of all thank you very much for your excellent work exposing Vulkan to .NET!
I started using it in my test project and while trying to add textures spotted a bug in generated code for PhysicalDevice.GetFormatProperties(). I believe the second parameter should be with out signature.
I can send you a patch for Functions.cs but since it is generated you probably better fix the template.
Best Regards,
Boris.

**Comment by jwollen** [comment]
Thanks for the report!
Fixed
