### ISSUE TITLE
Setting validate to true in MiniTri results in Vulkan error ValidationFailed

### ISSUE THREAD

**Issue by jcoder58** [jwollen/SharpVulkan#7]
SharpVulkan.dll!SharpVulkan.ResultExtensions.CheckError(SharpVulkan.Result result) Line 29	C#
	SharpVulkan.dll!SharpVulkan.Device.CreateGraphicsPipelines(SharpVulkan.PipelineCache pipelineCache, uint createInfoCount, SharpVulkan.GraphicsPipelineCreateInfo* createInfos, SharpVulkan.AllocationCallbacks* allocator) Line 876	C#
 	MiniTri.exe!MiniTri.Sample.CreatePipeline() Line 600	C#
 	MiniTri.exe!MiniTri.Sample.Initialize() Line 96	C#
 	MiniTri.exe!MiniTri.Sample.Run() Line 79	C#
 	MiniTri.exe!MiniTri.Program.Main() Line 32	C#

Vulkan reports:

Error: Attempt to set lineWidth to 0.000000 but physical device wideLines feature not supported/enabled so lineWidth must be 1.0f! ([10] DS)
Warning: vkCreateGraphicsPipelines: returned VK_ERROR_VALIDATION_FAILED_EXT, indicating that API validation has detected an invalid use of the API ([1] ParameterValidation)

**Comment by stefnotch** [comment]
You could post your source code or the relevant lines that cause an error. It looks like your GPU doesn't like line widths that are not 1.

**Comment by jcoder58** [comment]
In your project MiniTri, in Sample.cs line 37, change validate = false to validate = true.  Compile and run.  No other code changes.

Driver is Nvidia Version 365.19.  GPU is GTX870M

**Comment by jwollen** [comment]
Thanks for the report!
Should be fixed.

Out of curiosity, what video card do you use?

**Comment by jcoder58** [comment]
>Out of curiosity, what video card do you use?

I have an MSI GT70 2PC laptop with an embedded Nvidia 870M GPU.
